// DOM element references
export const elements = {
    noteInput: document.getElementById("noteInput"),
    noteDisplay: document.getElementById("noteDisplay"),
    noteEditorContainer: document.getElementById("noteEditorContainer"),
    noteDisplayContainer: document.getElementById("noteDisplayContainer"),
    processingOverlay: document.getElementById("processingOverlay"),
    fileInput: document.getElementById("fileInput"),
    dropZone: document.getElementById("dropZone"),
    browseBtn: document.getElementById("browseBtn"),
    submitBtn: document.getElementById("submitBtn"),
    submitCodesBtn: document.getElementById("submitCodesBtn"),
    saveChangesBtn: document.getElementById("saveChangesBtn"),
    resetBtn: document.getElementById("resetBtn"),
    clearHighlightsBtn: document.getElementById("clearHighlightsBtn"),
    clearFinalizedBtn: document.getElementById("clearFinalizedBtn"),
    modelSelect: document.getElementById("modelSelect"),
    methodSelect: document.getElementById("methodSelect"),
    thresholdInput: document.getElementById("thresholdInput"),
    codesContainer: document.getElementById("codesContainer"),
    cptCodesContainer: document.getElementById("cptCodesContainer"),
    finalizedContainer: document.getElementById("finalizedContainer"),
    statusBar: document.getElementById("statusBar"),
    searchInput: document.getElementById("codeSearch"),
    codeSearchResults: document.getElementById("codeSearchResults"),
    codeSearchAddBtn: document.getElementById("codeSearchAddBtn"),
    cptSearchInput: document.getElementById("cptCodeSearch"),
    cptSearchResults: document.getElementById("cptSearchResults"),
    cptSearchAddBtn: document.getElementById("cptSearchAddBtn"),
    noteFilename: document.getElementById("noteFilename"),
    modeSelect: document.getElementById("modeSelect"),
    folderNameModal: document.getElementById("folderNameModal"),
    folderNameInput: document.getElementById("folderNameInput"),
    folderNameSubmitBtn: document.getElementById("folderNameSubmitBtn"),
    folderNameCancelBtn: document.getElementById("folderNameCancelBtn"),
    modeSelectWrapper: document.getElementById("modeSelectWrapper"),
    llmModelWrapper: document.getElementById("llmModelWrapper"),
    llmModelSelect: document.getElementById("llmModelSelect"),
    modelSelectWrapper: document.getElementById("modelSelectWrapper"),
    methodSelectWrapper: document.getElementById("methodSelectWrapper"),
    thresholdWrapper: document.getElementById("thresholdWrapper"),
    icdVersionToggle: document.getElementById("icdVersionToggle"),
    icdVersionWrapper: document.getElementById("icdVersionWrapper"),
    lookupCodeTypeToggle: document.getElementById("lookupCodeTypeToggle"),
    lookupCodeTypeWrapper: document.getElementById("lookupCodeTypeWrapper"),
    lookupIcdVersionToggle: document.getElementById("lookupIcdVersionToggle"),
    lookupIcdVersionWrapper: document.getElementById("lookupIcdVersionWrapper"),
    aiCodeTypeToggle: document.getElementById("aiCodeTypeToggle"),
    aiCodeTypeToggleWrapper: document.getElementById("aiCodeTypeToggleWrapper"),
    aiHeaderActions: document.getElementById("aiHeaderActions"),
    resetAISuggestionsBtn: document.getElementById("resetAISuggestionsBtn"),
    codeTabs: document.getElementById("codeTabs"),
    icdTab: document.getElementById("icdTab"),
    cptTab: document.getElementById("cptTab"),
    icdTabContent: document.getElementById("icdTabContent"),
    cptTabContent: document.getElementById("cptTabContent"),
    modeTabsContainer: document.querySelector(".mode-tabs"),
    modeTabs: Array.from(document.querySelectorAll(".mode-tab")),
    appMain: document.querySelector(".app-main"),
    sidebar: document.querySelector(".sidebar"),
    inferenceControls: document.getElementById("inferenceControls"),
    suggestionsSection: document.querySelector(".sidebar-section.suggestions"),
    finalizedSection: document.querySelector(".sidebar-section.finalized"),
    sidebarHeader: document.querySelector(".sidebar-header"),
    sidebarTitle: document.querySelector(".sidebar-header h2"),
    sidebarHint: document.querySelector(".sidebar-header p"),
    folderBrowser: document.getElementById("folderBrowser"),
    folderList: document.getElementById("folderList"),
    refreshFoldersBtn: document.getElementById("refreshFoldersBtn"),
    clearFoldersBtn: document.getElementById("clearFoldersBtn"),
    folderSearchInput: document.getElementById("folderSearchInput"),
    admissionIdWrapper: document.getElementById("admissionIdWrapper"),
    admissionIdInput: document.getElementById("admissionIdInput"),
    manualLookupIcd: document.querySelector("#icdTabContent .lookup-panel"),
    manualLookupCpt: document.querySelector("#cptTabContent .lookup-panel"),
    aiPanelIcd: document.querySelector("#icdTabContent .ai-panel"),
    aiPanelCpt: document.querySelector("#cptTabContent .ai-panel"),
};

export const submitButtonDefaultText = elements.submitBtn ? elements.submitBtn.textContent : "Submit";
export const submitCodesButtonDefaultText = elements.submitCodesBtn ? elements.submitCodesBtn.textContent : "Submit Codes";
export const placeholderText = "Paste or type clinical note here...";

